config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :stores, defaults: { format: :json }
  resources :articles, defaults: { format: :json }
  resources :lists, defaults: { format: :json }
  resource :clip, only: [:create, :destroy], defaults: { format: :json }

  get '/timeline', to: 'timeline#index', defaults: { format: :json }

  namespace :admin do
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :stores, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :official_accounts, -> { where(official: true) }, class_name: 'User'
  has_many :articles
  has_many :store_images

  accepts_nested_attributes_for :store_images

  include Prefecture
end

app/controllers/admin/stores_controller.rb
module Admin
  class StoresController < AdminController
    before_action :set_store, only: [:edit, :update, :destroy]
    def index
      @stores = Store.where(search_params).page(params[:page]).per(20)
    end

    def new
      @store = Store.new
      3.times { @store.store_images.build }
    end

    def create
      @store = Store.new(stores_params)
      @store.validate!
      @store.save!
    end

    def edit; end

    def update
      @store.assign_attributes(stores_params)
      @store.validate!

      @store.save!
    end

    private

    def set_store
      @store = Store.find(params[:id])
    end

    def search_params
      params.permit(:page)
    end

    def stores_params
      params.require(:store).permit(
        :name, :prefecture_id, :address, :nearest_station, :phone_number, :commit,
        store_images_attributes: %i[image caption display_order]
      )
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show]
  def show
    @articles = @store.articles.page(params[:page]).per(20)
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end
end

app/views/admin/stores/_form.html.erb
<%= form_with model: [:admin, store] do |form| %>
<table>
  <thead></thead>
  <tbody>
    <tr>
      <th>店舗名</th>
      <td>
        <%= form.text_field :name %>
      </td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td>
        <input type="text" placeholder="999-9999"><button type="button" class="btn btn-primary">住所補完</button>
      </td>
    </tr>
    <tr>
      <th>都道府県</th>
      <td>
        <%= form.select :prefecture_id do %>
          <%= options_for_select(Store.prefecture_ids_i18n.map{ |k,v| [v, k] }) %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>住所</th>
      <td>
        <%= form.text_area :address %>
      </td>
    </tr>
    <tr>
      <th>最寄り駅</th>
      <td>
        <%= form.text_area :nearest_station %>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td>
        <%= form.phone_field :phone_number %>
      </td>
    </tr>
    <%= form.fields_for :store_images do |image_form| %>
    <tr>
      <th>画像</th>
      <td>
        <%= image_form.file_field :image %>
        <%= image_form.text_field :caption %>
        <%= image_form.number_field :display_order %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= form.submit %>
<% end %>

app/views/admin/stores/edit.html.erb
<%= render 'form', store: @store %>

app/views/admin/stores/index.html.erb
<h1># Stores Index</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>店舗名</th>
      <th>所在地</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do | store | %>
      <tr>
        <td><%= store.id %></td>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= link_to '編集', edit_admin_store_path(store) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @stores %>

app/views/admin/stores/new.html.erb
<%= render 'form', store: @store %>